### ISSUE TITLE
Share SWE573 GitHub repo address

### ISSUE THREAD

**Issue by ossarioglu** [ossarioglu/SWE574-Group2#2]
Team will share GitHub repo addresses for previous semester's work.
Items below will be reviewed offline:

- Requirements Analysis
- Elicitation
- Design Diagrams
- Coding
- Deployment

**Comment by ossarioglu** [comment]
Github repo for Osman Selcuk SARIOGLU is as follows:

[Osman's SWE573 Github](https://github.com/ossarioglu/SWE573-repo)

**Comment by sahar-avsh** [comment]
Github repo for Zahra Atrvash is as follows:

[Zahra's SWE573 Github](https://github.com/sahar-avsh/ZahraAtrvash-SWE573.git)

**Comment by SabriKorkmaz** [comment]
Github repo for Betül Güreş is as follows:

[Sabri's SWE573 Github](https://github.com/SabriKorkmaz/project-x)

**Comment by gokhanustuner** [comment]
Github repo for Gökhan Üstüner is as follows:

[Gökhan's SWE573 Github](https://github.com/gokhanustuner/swe-573-fall-2021)
