### ISSUE TITLE
Decide on labels in Github

### ISSUE THREAD

**Issue by ossarioglu** [ossarioglu/SWE574-Group2#8]
Check previous semester works and consolidate labels for Github.

**Comment by sahar-avsh** [comment]
- **Hard**
- **Not hard Not easy**
- **Easy**
- **Fronend**
- **Backend**

**Comment by gokhanustuner** [comment]
backend
bug
devops
requirements
research
priority:highest
priority:high
priority:medium
priority:low
priority:lowest
frontend

**Comment by ossarioglu** [comment]
We have agreed on standards on labeling:
- Start with small letters for new labels 
- Project features can be added
- Most frequently used ones are added
